plugin: amazon.aws.aws_ec2
regions:
  - us-east-1
  - us-east-2
keyed_groups:
  - key: tags.SSH
    prefix: ''
filters:
  tag:SSH: ['bastion', 'control_plane']
  instance-state-name: running
compose:
  ansible_host: private_ip_address
hostnames:
  - tag:SSH